apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-operator-ca
  namespace: openshift-machine-api
  annotations:
    release.openshift.io/delete: "true"
---
apiVersion: monitoring.coreos.com
kind: PrometheusRule
metadata:
  name: cluster-autoscaler-operator-rules
  namespace: openshift-machine-api
  annotations:
    release.openshift.io/delete: "true"
